### ISSUE TITLE
Crash: conurrent codification exception

### ISSUE THREAD

**Issue by genandnic** [Fuzss/skeletonaifix#1]
The game crashes when in a 2x1 corridor with a skeleton.
https://paste.dimdev.org/azusesihoj.mccrash

**Comment by Fuzss** [comment]
Thanks a lot for the report. Try the newest version of the mod (1.0.2 or even 1.0.1), the issue should hopefully be fixed there. Please tell me the result so I can either close this issue or look further into it.

**Comment by Fuzss** [comment]
Closing this now as it doesn't seem to been an issue in the latest version anymore.
